// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: communication.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Communication {

  /// <summary>Holder for reflection information generated from communication.proto</summary>
  public static partial class CommunicationReflection {

    #region Descriptor
    /// <summary>File descriptor for communication.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CommunicationReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNjb21tdW5pY2F0aW9uLnByb3RvEg1jb21tdW5pY2F0aW9uGgpnYW1lLnBy",
            "b3RvGg5kZWNpc2lvbi5wcm90bxoRcGF0aGZpbmRpbmcucHJvdG8aDmRhdGFi",
            "YXNlLnByb3RvIo0DCgxBc3luY1JlcXVlc3QSCgoCaWQYASABKAQSOgoRYWN0",
            "aXZpdHlTbmFwc2hvdHMYAiADKAsyHy5jb21tdW5pY2F0aW9uLkFjdGl2aXR5",
            "U25hcHNob3QSLQoKY29tYmF0RGF0YRgDIAEoCzIULmRlY2lzaW9uLkNvbWJh",
            "dERhdGFIAIgBARI6ChJwcm9ncmVzc2lvblJlcXVlc3QYBCABKAsyGS5kZWNp",
            "c2lvbi5Qcm9ncmVzc2lvbkRhdGFIAYgBARJAChJwYXRoZmluZGluZ1JlcXVl",
            "c3QYBSABKAsyHy5wYXRoZmluZGluZy5QYXRoZmluZGluZ1JlcXVlc3RIAogB",
            "ARI3Cg9kYXRhYmFzZVJlcXVlc3QYBiABKAsyGS5kYXRhYmFzZS5EYXRhYmFz",
            "ZVJlcXVlc3RIA4gBAUINCgtfY29tYmF0RGF0YUIVChNfcHJvZ3Jlc3Npb25S",
            "ZXF1ZXN0QhUKE19wYXRoZmluZGluZ1JlcXVlc3RCEgoQX2RhdGFiYXNlUmVx",
            "dWVzdCKWAQoQQWN0aXZpdHlTbmFwc2hvdBIRCgl0aW1lc3RhbXAYASABKA0S",
            "HwoGcGxheWVyGAIgASgLMg8uZ2FtZS5Xb1dQbGF5ZXISKgoNbmVhcmJ5T2Jq",
            "ZWN0cxgDIAMoCzITLmdhbWUuV29XR2FtZU9iamVjdBIiCgtuZWFyYnlVbml0",
            "cxgEIAMoCzINLmdhbWUuV29XVW5pdCJfCg5QbGF5ZXJTbmFwU2hvdBIMCgRy",
            "YWNlGAEgASgNEg0KBWNsYXNzGAIgASgNEiAKCHBvc2l0aW9uGAMgASgLMg4u",
            "Z2FtZS5Qb3NpdGlvbhIOCgZmYWNpbmcYBCABKAIiTgoMVW5pdFNuYXBTaG90",
            "EgwKBGd1aWQYASABKAQSIAoIcG9zaXRpb24YAiABKAsyDi5nYW1lLlBvc2l0",
            "aW9uEg4KBmZhY2luZxgDIAEoAiJzCg1BY3Rpb25NZXNzYWdlEi4KC2FjdGlv",
            "bl90eXBlGAEgASgOMhkuY29tbXVuaWNhdGlvbi5BY3Rpb25UeXBlEjIKCnBh",
            "cmFtZXRlcnMYAiADKAsyHi5jb21tdW5pY2F0aW9uLkFjdGlvblBhcmFtZXRl",
            "ciJ4Cg9BY3Rpb25QYXJhbWV0ZXISFQoLZmxvYXRfcGFyYW0YASABKAJIABIT",
            "CglpbnRfcGFyYW0YAiABKAVIABIUCgpsb25nX3BhcmFtGAMgASgDSAASFgoM",
            "c3RyaW5nX3BhcmFtGAQgASgJSABCCwoJcGFyYW1ldGVyIjoKCUFjdGlvbk1h",
            "cBItCgdhY3Rpb25zGAEgAygLMhwuY29tbXVuaWNhdGlvbi5BY3Rpb25NZXNz",
            "YWdlKpkICgpBY3Rpb25UeXBlEggKBFdBSVQQABIICgRHT1RPEAESEQoNSU5U",
            "RVJBQ1RfV0lUSBACEhEKDVNFTEVDVF9HT1NTSVAQAxIUChBTRUxFQ1RfVEFY",
            "SV9OT0RFEAQSEAoMQUNDRVBUX1FVRVNUEAUSEQoNREVDTElORV9RVUVTVBAG",
            "EhEKDVNFTEVDVF9SRVdBUkQQBxISCg5DT01QTEVURV9RVUVTVBAIEg8KC1RS",
            "QUlOX1NLSUxMEAkSEAoMVFJBSU5fVEFMRU5UEAoSDwoLT0ZGRVJfVFJBREUQ",
            "CxIOCgpPRkZFUl9HT0xEEAwSDgoKT0ZGRVJfSVRFTRANEhAKDEFDQ0VQVF9U",
            "UkFERRAOEhEKDURFQ0xJTkVfVFJBREUQDxIRCg1FTkNIQU5UX1RSQURFEBAS",
            "EgoOTE9DS1BJQ0tfVFJBREUQERISCg5QUk9NT1RFX0xFQURFUhASEhUKEVBS",
            "T01PVEVfQVNTSVNUQU5UEBMSGAoUUFJPTU9URV9MT09UX01BTkFHRVIQFBIS",
            "Cg5TRVRfR1JPVVBfTE9PVBAVEg8KC0FTU0lHTl9MT09UEBYSEgoOTE9PVF9S",
            "T0xMX05FRUQQFxITCg9MT09UX1JPTExfR1JFRUQQGBINCglMT09UX1BBU1MQ",
            "GRIVChFTRU5EX0dST1VQX0lOVklURRAaEhcKE0FDQ0VQVF9HUk9VUF9JTlZJ",
            "VEUQGxIYChRERUNMSU5FX0dST1VQX0lOVklURRAcEg8KC0tJQ0tfUExBWUVS",
            "EB0SDwoLTEVBVkVfR1JPVVAQHhIRCg1ESVNCQU5EX0dST1VQEB8SFgoSU1RB",
            "UlRfTUVMRUVfQVRUQUNLECASFwoTU1RBUlRfUkFOR0VEX0FUVEFDSxAhEhUK",
            "EVNUQVJUX1dBTkRfQVRUQUNLECISDwoLU1RPUF9BVFRBQ0sQIxIOCgpDQVNU",
            "X1NQRUxMECQSDQoJU1RPUF9DQVNUECUSDAoIVVNFX0lURU0QJhIOCgpFUVVJ",
            "UF9JVEVNECcSEAoMVU5FUVVJUF9JVEVNECgSEAoMREVTVFJPWV9JVEVNECkS",
            "DQoJTU9WRV9JVEVNECoSDwoLU1BMSVRfU1RBQ0sQKxIMCghCVVlfSVRFTRAs",
            "EhAKDEJVWUJBQ0tfSVRFTRAtEg0KCVNFTExfSVRFTRAuEg8KC1JFUEFJUl9J",
            "VEVNEC8SFAoQUkVQQUlSX0FMTF9JVEVNUxAwEhAKDERJU01JU1NfQlVGRhAx",
            "Eg0KCVJFU1VSUkVDVBAyEgkKBUNSQUZUEDMSCQoFTE9HSU4QNBIKCgZMT0dP",
            "VVQQNRIUChBDUkVBVEVfQ0hBUkFDVEVSEDYSFAoQREVMRVRFX0NIQVJBQ1RF",
            "UhA3Eg8KC0VOVEVSX1dPUkxEEDhiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Game.GameReflection.Descriptor, global::Decision.DecisionReflection.Descriptor, global::Pathfinding.PathfindingReflection.Descriptor, global::Database.DatabaseReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Communication.ActionType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Communication.AsyncRequest), global::Communication.AsyncRequest.Parser, new[]{ "Id", "ActivitySnapshots", "CombatData", "ProgressionRequest", "PathfindingRequest", "DatabaseRequest" }, new[]{ "CombatData", "ProgressionRequest", "PathfindingRequest", "DatabaseRequest" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Communication.ActivitySnapshot), global::Communication.ActivitySnapshot.Parser, new[]{ "Timestamp", "Player", "NearbyObjects", "NearbyUnits" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Communication.PlayerSnapShot), global::Communication.PlayerSnapShot.Parser, new[]{ "Race", "Class", "Position", "Facing" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Communication.UnitSnapShot), global::Communication.UnitSnapShot.Parser, new[]{ "Guid", "Position", "Facing" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Communication.ActionMessage), global::Communication.ActionMessage.Parser, new[]{ "ActionType", "Parameters" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Communication.ActionParameter), global::Communication.ActionParameter.Parser, new[]{ "FloatParam", "IntParam", "LongParam", "StringParam" }, new[]{ "Parameter" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Communication.ActionMap), global::Communication.ActionMap.Parser, new[]{ "Actions" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum ActionType {
    [pbr::OriginalName("WAIT")] Wait = 0,
    [pbr::OriginalName("GOTO")] Goto = 1,
    [pbr::OriginalName("INTERACT_WITH")] InteractWith = 2,
    [pbr::OriginalName("SELECT_GOSSIP")] SelectGossip = 3,
    [pbr::OriginalName("SELECT_TAXI_NODE")] SelectTaxiNode = 4,
    [pbr::OriginalName("ACCEPT_QUEST")] AcceptQuest = 5,
    [pbr::OriginalName("DECLINE_QUEST")] DeclineQuest = 6,
    [pbr::OriginalName("SELECT_REWARD")] SelectReward = 7,
    [pbr::OriginalName("COMPLETE_QUEST")] CompleteQuest = 8,
    [pbr::OriginalName("TRAIN_SKILL")] TrainSkill = 9,
    [pbr::OriginalName("TRAIN_TALENT")] TrainTalent = 10,
    [pbr::OriginalName("OFFER_TRADE")] OfferTrade = 11,
    [pbr::OriginalName("OFFER_GOLD")] OfferGold = 12,
    [pbr::OriginalName("OFFER_ITEM")] OfferItem = 13,
    [pbr::OriginalName("ACCEPT_TRADE")] AcceptTrade = 14,
    [pbr::OriginalName("DECLINE_TRADE")] DeclineTrade = 15,
    [pbr::OriginalName("ENCHANT_TRADE")] EnchantTrade = 16,
    [pbr::OriginalName("LOCKPICK_TRADE")] LockpickTrade = 17,
    [pbr::OriginalName("PROMOTE_LEADER")] PromoteLeader = 18,
    [pbr::OriginalName("PROMOTE_ASSISTANT")] PromoteAssistant = 19,
    [pbr::OriginalName("PROMOTE_LOOT_MANAGER")] PromoteLootManager = 20,
    [pbr::OriginalName("SET_GROUP_LOOT")] SetGroupLoot = 21,
    [pbr::OriginalName("ASSIGN_LOOT")] AssignLoot = 22,
    [pbr::OriginalName("LOOT_ROLL_NEED")] LootRollNeed = 23,
    [pbr::OriginalName("LOOT_ROLL_GREED")] LootRollGreed = 24,
    [pbr::OriginalName("LOOT_PASS")] LootPass = 25,
    [pbr::OriginalName("SEND_GROUP_INVITE")] SendGroupInvite = 26,
    [pbr::OriginalName("ACCEPT_GROUP_INVITE")] AcceptGroupInvite = 27,
    [pbr::OriginalName("DECLINE_GROUP_INVITE")] DeclineGroupInvite = 28,
    [pbr::OriginalName("KICK_PLAYER")] KickPlayer = 29,
    [pbr::OriginalName("LEAVE_GROUP")] LeaveGroup = 30,
    [pbr::OriginalName("DISBAND_GROUP")] DisbandGroup = 31,
    [pbr::OriginalName("START_MELEE_ATTACK")] StartMeleeAttack = 32,
    [pbr::OriginalName("START_RANGED_ATTACK")] StartRangedAttack = 33,
    [pbr::OriginalName("START_WAND_ATTACK")] StartWandAttack = 34,
    [pbr::OriginalName("STOP_ATTACK")] StopAttack = 35,
    [pbr::OriginalName("CAST_SPELL")] CastSpell = 36,
    [pbr::OriginalName("STOP_CAST")] StopCast = 37,
    [pbr::OriginalName("USE_ITEM")] UseItem = 38,
    [pbr::OriginalName("EQUIP_ITEM")] EquipItem = 39,
    [pbr::OriginalName("UNEQUIP_ITEM")] UnequipItem = 40,
    [pbr::OriginalName("DESTROY_ITEM")] DestroyItem = 41,
    [pbr::OriginalName("MOVE_ITEM")] MoveItem = 42,
    [pbr::OriginalName("SPLIT_STACK")] SplitStack = 43,
    [pbr::OriginalName("BUY_ITEM")] BuyItem = 44,
    [pbr::OriginalName("BUYBACK_ITEM")] BuybackItem = 45,
    [pbr::OriginalName("SELL_ITEM")] SellItem = 46,
    [pbr::OriginalName("REPAIR_ITEM")] RepairItem = 47,
    [pbr::OriginalName("REPAIR_ALL_ITEMS")] RepairAllItems = 48,
    [pbr::OriginalName("DISMISS_BUFF")] DismissBuff = 49,
    [pbr::OriginalName("RESURRECT")] Resurrect = 50,
    [pbr::OriginalName("CRAFT")] Craft = 51,
    [pbr::OriginalName("LOGIN")] Login = 52,
    [pbr::OriginalName("LOGOUT")] Logout = 53,
    [pbr::OriginalName("CREATE_CHARACTER")] CreateCharacter = 54,
    [pbr::OriginalName("DELETE_CHARACTER")] DeleteCharacter = 55,
    [pbr::OriginalName("ENTER_WORLD")] EnterWorld = 56,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AsyncRequest : pb::IMessage<AsyncRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AsyncRequest> _parser = new pb::MessageParser<AsyncRequest>(() => new AsyncRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AsyncRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Communication.CommunicationReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AsyncRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AsyncRequest(AsyncRequest other) : this() {
      id_ = other.id_;
      activitySnapshots_ = other.activitySnapshots_.Clone();
      combatData_ = other.combatData_ != null ? other.combatData_.Clone() : null;
      progressionRequest_ = other.progressionRequest_ != null ? other.progressionRequest_.Clone() : null;
      pathfindingRequest_ = other.pathfindingRequest_ != null ? other.pathfindingRequest_.Clone() : null;
      databaseRequest_ = other.databaseRequest_ != null ? other.databaseRequest_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AsyncRequest Clone() {
      return new AsyncRequest(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private ulong id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "activitySnapshots" field.</summary>
    public const int ActivitySnapshotsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Communication.ActivitySnapshot> _repeated_activitySnapshots_codec
        = pb::FieldCodec.ForMessage(18, global::Communication.ActivitySnapshot.Parser);
    private readonly pbc::RepeatedField<global::Communication.ActivitySnapshot> activitySnapshots_ = new pbc::RepeatedField<global::Communication.ActivitySnapshot>();
    /// <summary>
    /// Contains AsyncMessage requests to AsyncSocketServers. Needs a unique Id to track the client
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Communication.ActivitySnapshot> ActivitySnapshots {
      get { return activitySnapshots_; }
    }

    /// <summary>Field number for the "combatData" field.</summary>
    public const int CombatDataFieldNumber = 3;
    private global::Decision.CombatData combatData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Decision.CombatData CombatData {
      get { return combatData_; }
      set {
        combatData_ = value;
      }
    }

    /// <summary>Field number for the "progressionRequest" field.</summary>
    public const int ProgressionRequestFieldNumber = 4;
    private global::Decision.ProgressionData progressionRequest_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Decision.ProgressionData ProgressionRequest {
      get { return progressionRequest_; }
      set {
        progressionRequest_ = value;
      }
    }

    /// <summary>Field number for the "pathfindingRequest" field.</summary>
    public const int PathfindingRequestFieldNumber = 5;
    private global::Pathfinding.PathfindingRequest pathfindingRequest_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Pathfinding.PathfindingRequest PathfindingRequest {
      get { return pathfindingRequest_; }
      set {
        pathfindingRequest_ = value;
      }
    }

    /// <summary>Field number for the "databaseRequest" field.</summary>
    public const int DatabaseRequestFieldNumber = 6;
    private global::Database.DatabaseRequest databaseRequest_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Database.DatabaseRequest DatabaseRequest {
      get { return databaseRequest_; }
      set {
        databaseRequest_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AsyncRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AsyncRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if(!activitySnapshots_.Equals(other.activitySnapshots_)) return false;
      if (!object.Equals(CombatData, other.CombatData)) return false;
      if (!object.Equals(ProgressionRequest, other.ProgressionRequest)) return false;
      if (!object.Equals(PathfindingRequest, other.PathfindingRequest)) return false;
      if (!object.Equals(DatabaseRequest, other.DatabaseRequest)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0UL) hash ^= Id.GetHashCode();
      hash ^= activitySnapshots_.GetHashCode();
      if (combatData_ != null) hash ^= CombatData.GetHashCode();
      if (progressionRequest_ != null) hash ^= ProgressionRequest.GetHashCode();
      if (pathfindingRequest_ != null) hash ^= PathfindingRequest.GetHashCode();
      if (databaseRequest_ != null) hash ^= DatabaseRequest.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(Id);
      }
      activitySnapshots_.WriteTo(output, _repeated_activitySnapshots_codec);
      if (combatData_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(CombatData);
      }
      if (progressionRequest_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(ProgressionRequest);
      }
      if (pathfindingRequest_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(PathfindingRequest);
      }
      if (databaseRequest_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(DatabaseRequest);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(Id);
      }
      activitySnapshots_.WriteTo(ref output, _repeated_activitySnapshots_codec);
      if (combatData_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(CombatData);
      }
      if (progressionRequest_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(ProgressionRequest);
      }
      if (pathfindingRequest_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(PathfindingRequest);
      }
      if (databaseRequest_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(DatabaseRequest);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Id);
      }
      size += activitySnapshots_.CalculateSize(_repeated_activitySnapshots_codec);
      if (combatData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CombatData);
      }
      if (progressionRequest_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ProgressionRequest);
      }
      if (pathfindingRequest_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PathfindingRequest);
      }
      if (databaseRequest_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DatabaseRequest);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AsyncRequest other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0UL) {
        Id = other.Id;
      }
      activitySnapshots_.Add(other.activitySnapshots_);
      if (other.combatData_ != null) {
        if (combatData_ == null) {
          CombatData = new global::Decision.CombatData();
        }
        CombatData.MergeFrom(other.CombatData);
      }
      if (other.progressionRequest_ != null) {
        if (progressionRequest_ == null) {
          ProgressionRequest = new global::Decision.ProgressionData();
        }
        ProgressionRequest.MergeFrom(other.ProgressionRequest);
      }
      if (other.pathfindingRequest_ != null) {
        if (pathfindingRequest_ == null) {
          PathfindingRequest = new global::Pathfinding.PathfindingRequest();
        }
        PathfindingRequest.MergeFrom(other.PathfindingRequest);
      }
      if (other.databaseRequest_ != null) {
        if (databaseRequest_ == null) {
          DatabaseRequest = new global::Database.DatabaseRequest();
        }
        DatabaseRequest.MergeFrom(other.DatabaseRequest);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadUInt64();
            break;
          }
          case 18: {
            activitySnapshots_.AddEntriesFrom(input, _repeated_activitySnapshots_codec);
            break;
          }
          case 26: {
            if (combatData_ == null) {
              CombatData = new global::Decision.CombatData();
            }
            input.ReadMessage(CombatData);
            break;
          }
          case 34: {
            if (progressionRequest_ == null) {
              ProgressionRequest = new global::Decision.ProgressionData();
            }
            input.ReadMessage(ProgressionRequest);
            break;
          }
          case 42: {
            if (pathfindingRequest_ == null) {
              PathfindingRequest = new global::Pathfinding.PathfindingRequest();
            }
            input.ReadMessage(PathfindingRequest);
            break;
          }
          case 50: {
            if (databaseRequest_ == null) {
              DatabaseRequest = new global::Database.DatabaseRequest();
            }
            input.ReadMessage(DatabaseRequest);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadUInt64();
            break;
          }
          case 18: {
            activitySnapshots_.AddEntriesFrom(ref input, _repeated_activitySnapshots_codec);
            break;
          }
          case 26: {
            if (combatData_ == null) {
              CombatData = new global::Decision.CombatData();
            }
            input.ReadMessage(CombatData);
            break;
          }
          case 34: {
            if (progressionRequest_ == null) {
              ProgressionRequest = new global::Decision.ProgressionData();
            }
            input.ReadMessage(ProgressionRequest);
            break;
          }
          case 42: {
            if (pathfindingRequest_ == null) {
              PathfindingRequest = new global::Pathfinding.PathfindingRequest();
            }
            input.ReadMessage(PathfindingRequest);
            break;
          }
          case 50: {
            if (databaseRequest_ == null) {
              DatabaseRequest = new global::Database.DatabaseRequest();
            }
            input.ReadMessage(DatabaseRequest);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ActivitySnapshot : pb::IMessage<ActivitySnapshot>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ActivitySnapshot> _parser = new pb::MessageParser<ActivitySnapshot>(() => new ActivitySnapshot());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ActivitySnapshot> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Communication.CommunicationReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActivitySnapshot() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActivitySnapshot(ActivitySnapshot other) : this() {
      timestamp_ = other.timestamp_;
      player_ = other.player_ != null ? other.player_.Clone() : null;
      nearbyObjects_ = other.nearbyObjects_.Clone();
      nearbyUnits_ = other.nearbyUnits_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActivitySnapshot Clone() {
      return new ActivitySnapshot(this);
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 1;
    private uint timestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    /// <summary>Field number for the "player" field.</summary>
    public const int PlayerFieldNumber = 2;
    private global::Game.WoWPlayer player_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Game.WoWPlayer Player {
      get { return player_; }
      set {
        player_ = value;
      }
    }

    /// <summary>Field number for the "nearbyObjects" field.</summary>
    public const int NearbyObjectsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Game.WoWGameObject> _repeated_nearbyObjects_codec
        = pb::FieldCodec.ForMessage(26, global::Game.WoWGameObject.Parser);
    private readonly pbc::RepeatedField<global::Game.WoWGameObject> nearbyObjects_ = new pbc::RepeatedField<global::Game.WoWGameObject>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Game.WoWGameObject> NearbyObjects {
      get { return nearbyObjects_; }
    }

    /// <summary>Field number for the "nearbyUnits" field.</summary>
    public const int NearbyUnitsFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Game.WoWUnit> _repeated_nearbyUnits_codec
        = pb::FieldCodec.ForMessage(34, global::Game.WoWUnit.Parser);
    private readonly pbc::RepeatedField<global::Game.WoWUnit> nearbyUnits_ = new pbc::RepeatedField<global::Game.WoWUnit>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Game.WoWUnit> NearbyUnits {
      get { return nearbyUnits_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ActivitySnapshot);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ActivitySnapshot other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Timestamp != other.Timestamp) return false;
      if (!object.Equals(Player, other.Player)) return false;
      if(!nearbyObjects_.Equals(other.nearbyObjects_)) return false;
      if(!nearbyUnits_.Equals(other.nearbyUnits_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Timestamp != 0) hash ^= Timestamp.GetHashCode();
      if (player_ != null) hash ^= Player.GetHashCode();
      hash ^= nearbyObjects_.GetHashCode();
      hash ^= nearbyUnits_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Timestamp != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Timestamp);
      }
      if (player_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Player);
      }
      nearbyObjects_.WriteTo(output, _repeated_nearbyObjects_codec);
      nearbyUnits_.WriteTo(output, _repeated_nearbyUnits_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Timestamp != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Timestamp);
      }
      if (player_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Player);
      }
      nearbyObjects_.WriteTo(ref output, _repeated_nearbyObjects_codec);
      nearbyUnits_.WriteTo(ref output, _repeated_nearbyUnits_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Timestamp != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Timestamp);
      }
      if (player_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Player);
      }
      size += nearbyObjects_.CalculateSize(_repeated_nearbyObjects_codec);
      size += nearbyUnits_.CalculateSize(_repeated_nearbyUnits_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ActivitySnapshot other) {
      if (other == null) {
        return;
      }
      if (other.Timestamp != 0) {
        Timestamp = other.Timestamp;
      }
      if (other.player_ != null) {
        if (player_ == null) {
          Player = new global::Game.WoWPlayer();
        }
        Player.MergeFrom(other.Player);
      }
      nearbyObjects_.Add(other.nearbyObjects_);
      nearbyUnits_.Add(other.nearbyUnits_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Timestamp = input.ReadUInt32();
            break;
          }
          case 18: {
            if (player_ == null) {
              Player = new global::Game.WoWPlayer();
            }
            input.ReadMessage(Player);
            break;
          }
          case 26: {
            nearbyObjects_.AddEntriesFrom(input, _repeated_nearbyObjects_codec);
            break;
          }
          case 34: {
            nearbyUnits_.AddEntriesFrom(input, _repeated_nearbyUnits_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Timestamp = input.ReadUInt32();
            break;
          }
          case 18: {
            if (player_ == null) {
              Player = new global::Game.WoWPlayer();
            }
            input.ReadMessage(Player);
            break;
          }
          case 26: {
            nearbyObjects_.AddEntriesFrom(ref input, _repeated_nearbyObjects_codec);
            break;
          }
          case 34: {
            nearbyUnits_.AddEntriesFrom(ref input, _repeated_nearbyUnits_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PlayerSnapShot : pb::IMessage<PlayerSnapShot>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PlayerSnapShot> _parser = new pb::MessageParser<PlayerSnapShot>(() => new PlayerSnapShot());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PlayerSnapShot> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Communication.CommunicationReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerSnapShot() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerSnapShot(PlayerSnapShot other) : this() {
      race_ = other.race_;
      class_ = other.class_;
      position_ = other.position_ != null ? other.position_.Clone() : null;
      facing_ = other.facing_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerSnapShot Clone() {
      return new PlayerSnapShot(this);
    }

    /// <summary>Field number for the "race" field.</summary>
    public const int RaceFieldNumber = 1;
    private uint race_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Race {
      get { return race_; }
      set {
        race_ = value;
      }
    }

    /// <summary>Field number for the "class" field.</summary>
    public const int ClassFieldNumber = 2;
    private uint class_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Class {
      get { return class_; }
      set {
        class_ = value;
      }
    }

    /// <summary>Field number for the "position" field.</summary>
    public const int PositionFieldNumber = 3;
    private global::Game.Position position_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Game.Position Position {
      get { return position_; }
      set {
        position_ = value;
      }
    }

    /// <summary>Field number for the "facing" field.</summary>
    public const int FacingFieldNumber = 4;
    private float facing_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Facing {
      get { return facing_; }
      set {
        facing_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PlayerSnapShot);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PlayerSnapShot other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Race != other.Race) return false;
      if (Class != other.Class) return false;
      if (!object.Equals(Position, other.Position)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Facing, other.Facing)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Race != 0) hash ^= Race.GetHashCode();
      if (Class != 0) hash ^= Class.GetHashCode();
      if (position_ != null) hash ^= Position.GetHashCode();
      if (Facing != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Facing);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Race != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Race);
      }
      if (Class != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Class);
      }
      if (position_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Position);
      }
      if (Facing != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(Facing);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Race != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Race);
      }
      if (Class != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Class);
      }
      if (position_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Position);
      }
      if (Facing != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(Facing);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Race != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Race);
      }
      if (Class != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Class);
      }
      if (position_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Position);
      }
      if (Facing != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PlayerSnapShot other) {
      if (other == null) {
        return;
      }
      if (other.Race != 0) {
        Race = other.Race;
      }
      if (other.Class != 0) {
        Class = other.Class;
      }
      if (other.position_ != null) {
        if (position_ == null) {
          Position = new global::Game.Position();
        }
        Position.MergeFrom(other.Position);
      }
      if (other.Facing != 0F) {
        Facing = other.Facing;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Race = input.ReadUInt32();
            break;
          }
          case 16: {
            Class = input.ReadUInt32();
            break;
          }
          case 26: {
            if (position_ == null) {
              Position = new global::Game.Position();
            }
            input.ReadMessage(Position);
            break;
          }
          case 37: {
            Facing = input.ReadFloat();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Race = input.ReadUInt32();
            break;
          }
          case 16: {
            Class = input.ReadUInt32();
            break;
          }
          case 26: {
            if (position_ == null) {
              Position = new global::Game.Position();
            }
            input.ReadMessage(Position);
            break;
          }
          case 37: {
            Facing = input.ReadFloat();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class UnitSnapShot : pb::IMessage<UnitSnapShot>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UnitSnapShot> _parser = new pb::MessageParser<UnitSnapShot>(() => new UnitSnapShot());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UnitSnapShot> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Communication.CommunicationReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UnitSnapShot() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UnitSnapShot(UnitSnapShot other) : this() {
      guid_ = other.guid_;
      position_ = other.position_ != null ? other.position_.Clone() : null;
      facing_ = other.facing_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UnitSnapShot Clone() {
      return new UnitSnapShot(this);
    }

    /// <summary>Field number for the "guid" field.</summary>
    public const int GuidFieldNumber = 1;
    private ulong guid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Guid {
      get { return guid_; }
      set {
        guid_ = value;
      }
    }

    /// <summary>Field number for the "position" field.</summary>
    public const int PositionFieldNumber = 2;
    private global::Game.Position position_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Game.Position Position {
      get { return position_; }
      set {
        position_ = value;
      }
    }

    /// <summary>Field number for the "facing" field.</summary>
    public const int FacingFieldNumber = 3;
    private float facing_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Facing {
      get { return facing_; }
      set {
        facing_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UnitSnapShot);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UnitSnapShot other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Guid != other.Guid) return false;
      if (!object.Equals(Position, other.Position)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Facing, other.Facing)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Guid != 0UL) hash ^= Guid.GetHashCode();
      if (position_ != null) hash ^= Position.GetHashCode();
      if (Facing != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Facing);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Guid != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(Guid);
      }
      if (position_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Position);
      }
      if (Facing != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Facing);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Guid != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(Guid);
      }
      if (position_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Position);
      }
      if (Facing != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Facing);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Guid != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Guid);
      }
      if (position_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Position);
      }
      if (Facing != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UnitSnapShot other) {
      if (other == null) {
        return;
      }
      if (other.Guid != 0UL) {
        Guid = other.Guid;
      }
      if (other.position_ != null) {
        if (position_ == null) {
          Position = new global::Game.Position();
        }
        Position.MergeFrom(other.Position);
      }
      if (other.Facing != 0F) {
        Facing = other.Facing;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Guid = input.ReadUInt64();
            break;
          }
          case 18: {
            if (position_ == null) {
              Position = new global::Game.Position();
            }
            input.ReadMessage(Position);
            break;
          }
          case 29: {
            Facing = input.ReadFloat();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Guid = input.ReadUInt64();
            break;
          }
          case 18: {
            if (position_ == null) {
              Position = new global::Game.Position();
            }
            input.ReadMessage(Position);
            break;
          }
          case 29: {
            Facing = input.ReadFloat();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ActionMessage : pb::IMessage<ActionMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ActionMessage> _parser = new pb::MessageParser<ActionMessage>(() => new ActionMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ActionMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Communication.CommunicationReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActionMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActionMessage(ActionMessage other) : this() {
      actionType_ = other.actionType_;
      parameters_ = other.parameters_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActionMessage Clone() {
      return new ActionMessage(this);
    }

    /// <summary>Field number for the "action_type" field.</summary>
    public const int ActionTypeFieldNumber = 1;
    private global::Communication.ActionType actionType_ = global::Communication.ActionType.Wait;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Communication.ActionType ActionType {
      get { return actionType_; }
      set {
        actionType_ = value;
      }
    }

    /// <summary>Field number for the "parameters" field.</summary>
    public const int ParametersFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Communication.ActionParameter> _repeated_parameters_codec
        = pb::FieldCodec.ForMessage(18, global::Communication.ActionParameter.Parser);
    private readonly pbc::RepeatedField<global::Communication.ActionParameter> parameters_ = new pbc::RepeatedField<global::Communication.ActionParameter>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Communication.ActionParameter> Parameters {
      get { return parameters_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ActionMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ActionMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ActionType != other.ActionType) return false;
      if(!parameters_.Equals(other.parameters_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ActionType != global::Communication.ActionType.Wait) hash ^= ActionType.GetHashCode();
      hash ^= parameters_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ActionType != global::Communication.ActionType.Wait) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ActionType);
      }
      parameters_.WriteTo(output, _repeated_parameters_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ActionType != global::Communication.ActionType.Wait) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ActionType);
      }
      parameters_.WriteTo(ref output, _repeated_parameters_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ActionType != global::Communication.ActionType.Wait) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ActionType);
      }
      size += parameters_.CalculateSize(_repeated_parameters_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ActionMessage other) {
      if (other == null) {
        return;
      }
      if (other.ActionType != global::Communication.ActionType.Wait) {
        ActionType = other.ActionType;
      }
      parameters_.Add(other.parameters_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ActionType = (global::Communication.ActionType) input.ReadEnum();
            break;
          }
          case 18: {
            parameters_.AddEntriesFrom(input, _repeated_parameters_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ActionType = (global::Communication.ActionType) input.ReadEnum();
            break;
          }
          case 18: {
            parameters_.AddEntriesFrom(ref input, _repeated_parameters_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ActionParameter : pb::IMessage<ActionParameter>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ActionParameter> _parser = new pb::MessageParser<ActionParameter>(() => new ActionParameter());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ActionParameter> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Communication.CommunicationReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActionParameter() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActionParameter(ActionParameter other) : this() {
      switch (other.ParameterCase) {
        case ParameterOneofCase.FloatParam:
          FloatParam = other.FloatParam;
          break;
        case ParameterOneofCase.IntParam:
          IntParam = other.IntParam;
          break;
        case ParameterOneofCase.LongParam:
          LongParam = other.LongParam;
          break;
        case ParameterOneofCase.StringParam:
          StringParam = other.StringParam;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActionParameter Clone() {
      return new ActionParameter(this);
    }

    /// <summary>Field number for the "float_param" field.</summary>
    public const int FloatParamFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float FloatParam {
      get { return HasFloatParam ? (float) parameter_ : 0F; }
      set {
        parameter_ = value;
        parameterCase_ = ParameterOneofCase.FloatParam;
      }
    }
    /// <summary>Gets whether the "float_param" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasFloatParam {
      get { return parameterCase_ == ParameterOneofCase.FloatParam; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "float_param" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearFloatParam() {
      if (HasFloatParam) {
        ClearParameter();
      }
    }

    /// <summary>Field number for the "int_param" field.</summary>
    public const int IntParamFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int IntParam {
      get { return HasIntParam ? (int) parameter_ : 0; }
      set {
        parameter_ = value;
        parameterCase_ = ParameterOneofCase.IntParam;
      }
    }
    /// <summary>Gets whether the "int_param" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasIntParam {
      get { return parameterCase_ == ParameterOneofCase.IntParam; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "int_param" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearIntParam() {
      if (HasIntParam) {
        ClearParameter();
      }
    }

    /// <summary>Field number for the "long_param" field.</summary>
    public const int LongParamFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long LongParam {
      get { return HasLongParam ? (long) parameter_ : 0L; }
      set {
        parameter_ = value;
        parameterCase_ = ParameterOneofCase.LongParam;
      }
    }
    /// <summary>Gets whether the "long_param" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasLongParam {
      get { return parameterCase_ == ParameterOneofCase.LongParam; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "long_param" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearLongParam() {
      if (HasLongParam) {
        ClearParameter();
      }
    }

    /// <summary>Field number for the "string_param" field.</summary>
    public const int StringParamFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string StringParam {
      get { return HasStringParam ? (string) parameter_ : ""; }
      set {
        parameter_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        parameterCase_ = ParameterOneofCase.StringParam;
      }
    }
    /// <summary>Gets whether the "string_param" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasStringParam {
      get { return parameterCase_ == ParameterOneofCase.StringParam; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "string_param" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearStringParam() {
      if (HasStringParam) {
        ClearParameter();
      }
    }

    private object parameter_;
    /// <summary>Enum of possible cases for the "parameter" oneof.</summary>
    public enum ParameterOneofCase {
      None = 0,
      FloatParam = 1,
      IntParam = 2,
      LongParam = 3,
      StringParam = 4,
    }
    private ParameterOneofCase parameterCase_ = ParameterOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ParameterOneofCase ParameterCase {
      get { return parameterCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearParameter() {
      parameterCase_ = ParameterOneofCase.None;
      parameter_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ActionParameter);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ActionParameter other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(FloatParam, other.FloatParam)) return false;
      if (IntParam != other.IntParam) return false;
      if (LongParam != other.LongParam) return false;
      if (StringParam != other.StringParam) return false;
      if (ParameterCase != other.ParameterCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasFloatParam) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(FloatParam);
      if (HasIntParam) hash ^= IntParam.GetHashCode();
      if (HasLongParam) hash ^= LongParam.GetHashCode();
      if (HasStringParam) hash ^= StringParam.GetHashCode();
      hash ^= (int) parameterCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasFloatParam) {
        output.WriteRawTag(13);
        output.WriteFloat(FloatParam);
      }
      if (HasIntParam) {
        output.WriteRawTag(16);
        output.WriteInt32(IntParam);
      }
      if (HasLongParam) {
        output.WriteRawTag(24);
        output.WriteInt64(LongParam);
      }
      if (HasStringParam) {
        output.WriteRawTag(34);
        output.WriteString(StringParam);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasFloatParam) {
        output.WriteRawTag(13);
        output.WriteFloat(FloatParam);
      }
      if (HasIntParam) {
        output.WriteRawTag(16);
        output.WriteInt32(IntParam);
      }
      if (HasLongParam) {
        output.WriteRawTag(24);
        output.WriteInt64(LongParam);
      }
      if (HasStringParam) {
        output.WriteRawTag(34);
        output.WriteString(StringParam);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasFloatParam) {
        size += 1 + 4;
      }
      if (HasIntParam) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(IntParam);
      }
      if (HasLongParam) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(LongParam);
      }
      if (HasStringParam) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StringParam);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ActionParameter other) {
      if (other == null) {
        return;
      }
      switch (other.ParameterCase) {
        case ParameterOneofCase.FloatParam:
          FloatParam = other.FloatParam;
          break;
        case ParameterOneofCase.IntParam:
          IntParam = other.IntParam;
          break;
        case ParameterOneofCase.LongParam:
          LongParam = other.LongParam;
          break;
        case ParameterOneofCase.StringParam:
          StringParam = other.StringParam;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 13: {
            FloatParam = input.ReadFloat();
            break;
          }
          case 16: {
            IntParam = input.ReadInt32();
            break;
          }
          case 24: {
            LongParam = input.ReadInt64();
            break;
          }
          case 34: {
            StringParam = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 13: {
            FloatParam = input.ReadFloat();
            break;
          }
          case 16: {
            IntParam = input.ReadInt32();
            break;
          }
          case 24: {
            LongParam = input.ReadInt64();
            break;
          }
          case 34: {
            StringParam = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ActionMap : pb::IMessage<ActionMap>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ActionMap> _parser = new pb::MessageParser<ActionMap>(() => new ActionMap());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ActionMap> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Communication.CommunicationReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActionMap() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActionMap(ActionMap other) : this() {
      actions_ = other.actions_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActionMap Clone() {
      return new ActionMap(this);
    }

    /// <summary>Field number for the "actions" field.</summary>
    public const int ActionsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Communication.ActionMessage> _repeated_actions_codec
        = pb::FieldCodec.ForMessage(10, global::Communication.ActionMessage.Parser);
    private readonly pbc::RepeatedField<global::Communication.ActionMessage> actions_ = new pbc::RepeatedField<global::Communication.ActionMessage>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Communication.ActionMessage> Actions {
      get { return actions_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ActionMap);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ActionMap other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!actions_.Equals(other.actions_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= actions_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      actions_.WriteTo(output, _repeated_actions_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      actions_.WriteTo(ref output, _repeated_actions_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += actions_.CalculateSize(_repeated_actions_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ActionMap other) {
      if (other == null) {
        return;
      }
      actions_.Add(other.actions_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            actions_.AddEntriesFrom(input, _repeated_actions_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            actions_.AddEntriesFrom(ref input, _repeated_actions_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
