// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: communication.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Communication {

  /// <summary>Holder for reflection information generated from communication.proto</summary>
  public static partial class CommunicationReflection {

    #region Descriptor
    /// <summary>File descriptor for communication.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CommunicationReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNjb21tdW5pY2F0aW9uLnByb3RvEg1jb21tdW5pY2F0aW9uIqsBCgtEYXRh",
            "TWVzc2FnZRIKCgJpZBgBIAEoBBI+ChB3b3JsZFN0YXRlVXBkYXRlGAIgASgL",
            "Mh8uY29tbXVuaWNhdGlvbi5Xb3JsZFN0YXRlVXBkYXRlSACIAQESLgoIYWN0",
            "aXZpdHkYBCABKAsyFy5jb21tdW5pY2F0aW9uLkFjdGl2aXR5SAGIAQFCEwoR",
            "X3dvcmxkU3RhdGVVcGRhdGVCCwoJX2FjdGl2aXR5IjkKCldvcmxkU3RhdGUS",
            "KwoKYWN0aXZpdGllcxgBIAMoCzIXLmNvbW11bmljYXRpb24uQWN0aXZpdHki",
            "cwoIQWN0aXZpdHkSKQoEdHlwZRgBIAEoDjIbLmNvbW11bmljYXRpb24uQWN0",
            "aXZpdHlUeXBlEgwKBHBvcnQYAiABKA0SLgoHbWVtYmVycxgDIAMoCzIdLmNv",
            "bW11bmljYXRpb24uQWN0aXZpdHlNZW1iZXIiiwEKDkFjdGl2aXR5TWVtYmVy",
            "EhcKD2JlaGF2aW9yUHJvZmlsZRgBIAEoCRITCgthY2NvdW50TmFtZRgCIAEo",
            "CRIaChJwcm9ncmVzc2lvblByb2ZpbGUYAyABKAkSFgoOaW5pdGlhbFByb2Zp",
            "bGUYBCABKAkSFwoPZW5kU3RhdGVQcm9maWxlGAUgASgJIoYBChNBY3Rpdml0",
            "eU1lbWJlclN0YXRlEi0KBm1lbWJlchgBIAEoCzIdLmNvbW11bmljYXRpb24u",
            "QWN0aXZpdHlNZW1iZXISDAoEZ3VpZBgCIAEoBBIOCgZJblJhaWQYAyABKAgS",
            "EQoJUGV0U3BlbGxzGAQgAygNEg8KB1RhbGVudHMYBSADKA0igQEKEFdvcmxk",
            "U3RhdGVVcGRhdGUSLQoGYWN0aW9uGAEgASgOMh0uY29tbXVuaWNhdGlvbi5B",
            "Y3Rpdml0eUFjdGlvbhIOCgZwYXJhbTEYAiABKAkSDgoGcGFyYW0yGAMgASgJ",
            "Eg4KBnBhcmFtMxgEIAEoCRIOCgZwYXJhbTQYBSABKAkqrwEKDkFjdGl2aXR5",
            "QWN0aW9uEggKBE5vbmUQABIPCgtBZGRBY3Rpdml0eRABEhAKDEVkaXRBY3Rp",
            "dml0eRACEhUKEUFkZEFjdGl2aXR5TWVtYmVyEAMSFgoSRWRpdEFjdGl2aXR5",
            "TWVtYmVyEAQSFAoQU2V0TWluTWVtYmVyU2l6ZRAFEhQKEFNldE1heE1lbWJl",
            "clNpemUQBhIVChFBcHBseURlc2lyZWRTdGF0ZRAHKpkICgxBY3Rpdml0eVR5",
            "cGUSCAoESWRsZRAAEhUKEVB2UFdhcnNvbmdHdWxjaDE5EAESFQoRUHZQV2Fy",
            "c29uZ0d1bGNoMjkQAhIVChFQdlBXYXJzb25nR3VsY2gzORADEhUKEVB2UFdh",
            "cnNvbmdHdWxjaDQ5EAQSFQoRUHZQV2Fyc29uZ0d1bGNoNTkQBRIVChFQdlBX",
            "YXJzb25nR3VsY2g2MBAGEhQKEFB2UEFyYXRoaUJhc2luMjkQBxIUChBQdlBB",
            "cmF0aGlCYXNpbjM5EAgSFAoQUHZQQXJhdGhpQmFzaW40ORAJEhQKEFB2UEFy",
            "YXRoaUJhc2luNTkQChIUChBQdlBBcmF0aGlCYXNpbjYwEAsSFAoQUHZQQWx0",
            "ZXJhY1ZhbGxleRAMEhQKEFB2RVJhZ2VmaXJlQ2hhc20QDRIVChFQdkVXYWls",
            "aW5nQ2F2ZXJucxAOEhMKD1B2RVRoZURlYWRtaW5lcxAPEhUKEVB2RVNoYWRv",
            "d2ZhbmdLZWVwEBASEgoOUHZFVGhlU3RvY2thZGUQERIUChBQdkVSYXpvcmZl",
            "bktyYXVsEBISFwoTUHZFQmxhY2tmYXRob21EZWVwcxATEhEKDVB2RUdub21l",
            "cmVnYW4QFBISCg5QdkVTTUdyYXZleWFyZBAVEhAKDFB2RVNNTGlicmFyeRAW",
            "Eg8KC1B2RVNNQXJtb3J5EBcSEgoOUHZFU01DYXRoZWRyYWwQGBIUChBQdkVS",
            "YXpvcmZlbkRvd25zEBkSDgoKUHZFVWxkYW1hbhAaEhAKDFB2RVp1bEZhcnJh",
            "axAbEhsKF1B2RU1hcmF1ZG9uV2lja2VkR3JvdHRvEBwSHgoaUHZFTWFyYXVk",
            "b25Gb3Vsc3BvcmVDYXZlcm4QHRIdChlQdkVNYXJhdWRvbkVhcnRoU29uZ0Zh",
            "bGxzEB4SGQoVUHZFVGVtcGxlT2ZBdGFsSGFra2FyEB8SFgoSUHZFQmxhY2ty",
            "b2NrRGVwdGhzECASGgoWUHZFTG93ZXJCbGFja3JvY2tTcGlyZRAhEhoKFlB2",
            "RVVwcGVyQmxhY2tyb2NrU3BpcmUQIhIPCgtQdkVEaXJlTWF1bBAjEhYKElB2",
            "RVN0cmF0aG9sbWVBbGl2ZRAkEhcKE1B2RVN0cmF0aG9sbWVVbmRlYWQQJRIS",
            "Cg5QdkVTY2hvbG9tYW5jZRAmEhIKDlB2RU9ueXhpYXNMYWlyECcSDwoLUHZF",
            "WnVsR3VydWIQKBIRCg1QdkVNb2x0ZW5Db3JlECkSFAoQUHZFQmxhY2t3aW5n",
            "TGFpchAqEhYKElB2RVJ1aW5zT2ZBaG5RaXJhahArEhcKE1B2RVRlbXBsZU9m",
            "QWhuUWlyYWoQLBIQCgxQdkVOYXh4cmFtYXMQLRIRCg1QdkVIb2dnZXJSYWlk",
            "EC5iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Communication.ActivityAction), typeof(global::Communication.ActivityType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Communication.DataMessage), global::Communication.DataMessage.Parser, new[]{ "Id", "WorldStateUpdate", "Activity" }, new[]{ "WorldStateUpdate", "Activity" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Communication.WorldState), global::Communication.WorldState.Parser, new[]{ "Activities" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Communication.Activity), global::Communication.Activity.Parser, new[]{ "Type", "Port", "Members" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Communication.ActivityMember), global::Communication.ActivityMember.Parser, new[]{ "BehaviorProfile", "AccountName", "ProgressionProfile", "InitialProfile", "EndStateProfile" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Communication.ActivityMemberState), global::Communication.ActivityMemberState.Parser, new[]{ "Member", "Guid", "InRaid", "PetSpells", "Talents" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Communication.WorldStateUpdate), global::Communication.WorldStateUpdate.Parser, new[]{ "Action", "Param1", "Param2", "Param3", "Param4" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum ActivityAction {
    [pbr::OriginalName("None")] None = 0,
    [pbr::OriginalName("AddActivity")] AddActivity = 1,
    [pbr::OriginalName("EditActivity")] EditActivity = 2,
    [pbr::OriginalName("AddActivityMember")] AddActivityMember = 3,
    [pbr::OriginalName("EditActivityMember")] EditActivityMember = 4,
    [pbr::OriginalName("SetMinMemberSize")] SetMinMemberSize = 5,
    [pbr::OriginalName("SetMaxMemberSize")] SetMaxMemberSize = 6,
    [pbr::OriginalName("ApplyDesiredState")] ApplyDesiredState = 7,
  }

  public enum ActivityType {
    [pbr::OriginalName("Idle")] Idle = 0,
    [pbr::OriginalName("PvPWarsongGulch19")] PvPwarsongGulch19 = 1,
    [pbr::OriginalName("PvPWarsongGulch29")] PvPwarsongGulch29 = 2,
    [pbr::OriginalName("PvPWarsongGulch39")] PvPwarsongGulch39 = 3,
    [pbr::OriginalName("PvPWarsongGulch49")] PvPwarsongGulch49 = 4,
    [pbr::OriginalName("PvPWarsongGulch59")] PvPwarsongGulch59 = 5,
    [pbr::OriginalName("PvPWarsongGulch60")] PvPwarsongGulch60 = 6,
    [pbr::OriginalName("PvPArathiBasin29")] PvParathiBasin29 = 7,
    [pbr::OriginalName("PvPArathiBasin39")] PvParathiBasin39 = 8,
    [pbr::OriginalName("PvPArathiBasin49")] PvParathiBasin49 = 9,
    [pbr::OriginalName("PvPArathiBasin59")] PvParathiBasin59 = 10,
    [pbr::OriginalName("PvPArathiBasin60")] PvParathiBasin60 = 11,
    [pbr::OriginalName("PvPAlteracValley")] PvPalteracValley = 12,
    [pbr::OriginalName("PvERagefireChasm")] PvEragefireChasm = 13,
    [pbr::OriginalName("PvEWailingCaverns")] PvEwailingCaverns = 14,
    [pbr::OriginalName("PvETheDeadmines")] PvEtheDeadmines = 15,
    [pbr::OriginalName("PvEShadowfangKeep")] PvEshadowfangKeep = 16,
    [pbr::OriginalName("PvETheStockade")] PvEtheStockade = 17,
    [pbr::OriginalName("PvERazorfenKraul")] PvErazorfenKraul = 18,
    [pbr::OriginalName("PvEBlackfathomDeeps")] PvEblackfathomDeeps = 19,
    [pbr::OriginalName("PvEGnomeregan")] PvEgnomeregan = 20,
    [pbr::OriginalName("PvESMGraveyard")] PvEsmgraveyard = 21,
    [pbr::OriginalName("PvESMLibrary")] PvEsmlibrary = 22,
    [pbr::OriginalName("PvESMArmory")] PvEsmarmory = 23,
    [pbr::OriginalName("PvESMCathedral")] PvEsmcathedral = 24,
    [pbr::OriginalName("PvERazorfenDowns")] PvErazorfenDowns = 25,
    [pbr::OriginalName("PvEUldaman")] PvEuldaman = 26,
    [pbr::OriginalName("PvEZulFarrak")] PvEzulFarrak = 27,
    [pbr::OriginalName("PvEMaraudonWickedGrotto")] PvEmaraudonWickedGrotto = 28,
    [pbr::OriginalName("PvEMaraudonFoulsporeCavern")] PvEmaraudonFoulsporeCavern = 29,
    [pbr::OriginalName("PvEMaraudonEarthSongFalls")] PvEmaraudonEarthSongFalls = 30,
    [pbr::OriginalName("PvETempleOfAtalHakkar")] PvEtempleOfAtalHakkar = 31,
    [pbr::OriginalName("PvEBlackrockDepths")] PvEblackrockDepths = 32,
    [pbr::OriginalName("PvELowerBlackrockSpire")] PvElowerBlackrockSpire = 33,
    [pbr::OriginalName("PvEUpperBlackrockSpire")] PvEupperBlackrockSpire = 34,
    [pbr::OriginalName("PvEDireMaul")] PvEdireMaul = 35,
    [pbr::OriginalName("PvEStratholmeAlive")] PvEstratholmeAlive = 36,
    [pbr::OriginalName("PvEStratholmeUndead")] PvEstratholmeUndead = 37,
    [pbr::OriginalName("PvEScholomance")] PvEscholomance = 38,
    [pbr::OriginalName("PvEOnyxiasLair")] PvEonyxiasLair = 39,
    [pbr::OriginalName("PvEZulGurub")] PvEzulGurub = 40,
    [pbr::OriginalName("PvEMoltenCore")] PvEmoltenCore = 41,
    [pbr::OriginalName("PvEBlackwingLair")] PvEblackwingLair = 42,
    [pbr::OriginalName("PvERuinsOfAhnQiraj")] PvEruinsOfAhnQiraj = 43,
    [pbr::OriginalName("PvETempleOfAhnQiraj")] PvEtempleOfAhnQiraj = 44,
    [pbr::OriginalName("PvENaxxramas")] PvEnaxxramas = 45,
    [pbr::OriginalName("PvEHoggerRaid")] PvEhoggerRaid = 46,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class DataMessage : pb::IMessage<DataMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DataMessage> _parser = new pb::MessageParser<DataMessage>(() => new DataMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DataMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Communication.CommunicationReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DataMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DataMessage(DataMessage other) : this() {
      id_ = other.id_;
      worldStateUpdate_ = other.worldStateUpdate_ != null ? other.worldStateUpdate_.Clone() : null;
      activity_ = other.activity_ != null ? other.activity_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DataMessage Clone() {
      return new DataMessage(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private ulong id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "worldStateUpdate" field.</summary>
    public const int WorldStateUpdateFieldNumber = 2;
    private global::Communication.WorldStateUpdate worldStateUpdate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Communication.WorldStateUpdate WorldStateUpdate {
      get { return worldStateUpdate_; }
      set {
        worldStateUpdate_ = value;
      }
    }

    /// <summary>Field number for the "activity" field.</summary>
    public const int ActivityFieldNumber = 4;
    private global::Communication.Activity activity_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Communication.Activity Activity {
      get { return activity_; }
      set {
        activity_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DataMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DataMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (!object.Equals(WorldStateUpdate, other.WorldStateUpdate)) return false;
      if (!object.Equals(Activity, other.Activity)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0UL) hash ^= Id.GetHashCode();
      if (worldStateUpdate_ != null) hash ^= WorldStateUpdate.GetHashCode();
      if (activity_ != null) hash ^= Activity.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(Id);
      }
      if (worldStateUpdate_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(WorldStateUpdate);
      }
      if (activity_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Activity);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(Id);
      }
      if (worldStateUpdate_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(WorldStateUpdate);
      }
      if (activity_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Activity);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Id);
      }
      if (worldStateUpdate_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(WorldStateUpdate);
      }
      if (activity_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Activity);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DataMessage other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0UL) {
        Id = other.Id;
      }
      if (other.worldStateUpdate_ != null) {
        if (worldStateUpdate_ == null) {
          WorldStateUpdate = new global::Communication.WorldStateUpdate();
        }
        WorldStateUpdate.MergeFrom(other.WorldStateUpdate);
      }
      if (other.activity_ != null) {
        if (activity_ == null) {
          Activity = new global::Communication.Activity();
        }
        Activity.MergeFrom(other.Activity);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadUInt64();
            break;
          }
          case 18: {
            if (worldStateUpdate_ == null) {
              WorldStateUpdate = new global::Communication.WorldStateUpdate();
            }
            input.ReadMessage(WorldStateUpdate);
            break;
          }
          case 34: {
            if (activity_ == null) {
              Activity = new global::Communication.Activity();
            }
            input.ReadMessage(Activity);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadUInt64();
            break;
          }
          case 18: {
            if (worldStateUpdate_ == null) {
              WorldStateUpdate = new global::Communication.WorldStateUpdate();
            }
            input.ReadMessage(WorldStateUpdate);
            break;
          }
          case 34: {
            if (activity_ == null) {
              Activity = new global::Communication.Activity();
            }
            input.ReadMessage(Activity);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class WorldState : pb::IMessage<WorldState>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WorldState> _parser = new pb::MessageParser<WorldState>(() => new WorldState());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WorldState> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Communication.CommunicationReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorldState() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorldState(WorldState other) : this() {
      activities_ = other.activities_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorldState Clone() {
      return new WorldState(this);
    }

    /// <summary>Field number for the "activities" field.</summary>
    public const int ActivitiesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Communication.Activity> _repeated_activities_codec
        = pb::FieldCodec.ForMessage(10, global::Communication.Activity.Parser);
    private readonly pbc::RepeatedField<global::Communication.Activity> activities_ = new pbc::RepeatedField<global::Communication.Activity>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Communication.Activity> Activities {
      get { return activities_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WorldState);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WorldState other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!activities_.Equals(other.activities_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= activities_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      activities_.WriteTo(output, _repeated_activities_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      activities_.WriteTo(ref output, _repeated_activities_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += activities_.CalculateSize(_repeated_activities_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WorldState other) {
      if (other == null) {
        return;
      }
      activities_.Add(other.activities_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            activities_.AddEntriesFrom(input, _repeated_activities_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            activities_.AddEntriesFrom(ref input, _repeated_activities_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Activity : pb::IMessage<Activity>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Activity> _parser = new pb::MessageParser<Activity>(() => new Activity());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Activity> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Communication.CommunicationReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Activity() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Activity(Activity other) : this() {
      type_ = other.type_;
      port_ = other.port_;
      members_ = other.members_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Activity Clone() {
      return new Activity(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Communication.ActivityType type_ = global::Communication.ActivityType.Idle;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Communication.ActivityType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "port" field.</summary>
    public const int PortFieldNumber = 2;
    private uint port_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Port {
      get { return port_; }
      set {
        port_ = value;
      }
    }

    /// <summary>Field number for the "members" field.</summary>
    public const int MembersFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Communication.ActivityMember> _repeated_members_codec
        = pb::FieldCodec.ForMessage(26, global::Communication.ActivityMember.Parser);
    private readonly pbc::RepeatedField<global::Communication.ActivityMember> members_ = new pbc::RepeatedField<global::Communication.ActivityMember>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Communication.ActivityMember> Members {
      get { return members_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Activity);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Activity other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (Port != other.Port) return false;
      if(!members_.Equals(other.members_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Communication.ActivityType.Idle) hash ^= Type.GetHashCode();
      if (Port != 0) hash ^= Port.GetHashCode();
      hash ^= members_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Communication.ActivityType.Idle) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Port != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Port);
      }
      members_.WriteTo(output, _repeated_members_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Communication.ActivityType.Idle) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Port != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Port);
      }
      members_.WriteTo(ref output, _repeated_members_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Communication.ActivityType.Idle) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Port != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Port);
      }
      size += members_.CalculateSize(_repeated_members_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Activity other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Communication.ActivityType.Idle) {
        Type = other.Type;
      }
      if (other.Port != 0) {
        Port = other.Port;
      }
      members_.Add(other.members_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Communication.ActivityType) input.ReadEnum();
            break;
          }
          case 16: {
            Port = input.ReadUInt32();
            break;
          }
          case 26: {
            members_.AddEntriesFrom(input, _repeated_members_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Communication.ActivityType) input.ReadEnum();
            break;
          }
          case 16: {
            Port = input.ReadUInt32();
            break;
          }
          case 26: {
            members_.AddEntriesFrom(ref input, _repeated_members_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ActivityMember : pb::IMessage<ActivityMember>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ActivityMember> _parser = new pb::MessageParser<ActivityMember>(() => new ActivityMember());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ActivityMember> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Communication.CommunicationReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActivityMember() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActivityMember(ActivityMember other) : this() {
      behaviorProfile_ = other.behaviorProfile_;
      accountName_ = other.accountName_;
      progressionProfile_ = other.progressionProfile_;
      initialProfile_ = other.initialProfile_;
      endStateProfile_ = other.endStateProfile_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActivityMember Clone() {
      return new ActivityMember(this);
    }

    /// <summary>Field number for the "behaviorProfile" field.</summary>
    public const int BehaviorProfileFieldNumber = 1;
    private string behaviorProfile_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string BehaviorProfile {
      get { return behaviorProfile_; }
      set {
        behaviorProfile_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "accountName" field.</summary>
    public const int AccountNameFieldNumber = 2;
    private string accountName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AccountName {
      get { return accountName_; }
      set {
        accountName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "progressionProfile" field.</summary>
    public const int ProgressionProfileFieldNumber = 3;
    private string progressionProfile_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ProgressionProfile {
      get { return progressionProfile_; }
      set {
        progressionProfile_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "initialProfile" field.</summary>
    public const int InitialProfileFieldNumber = 4;
    private string initialProfile_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string InitialProfile {
      get { return initialProfile_; }
      set {
        initialProfile_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "endStateProfile" field.</summary>
    public const int EndStateProfileFieldNumber = 5;
    private string endStateProfile_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string EndStateProfile {
      get { return endStateProfile_; }
      set {
        endStateProfile_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ActivityMember);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ActivityMember other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BehaviorProfile != other.BehaviorProfile) return false;
      if (AccountName != other.AccountName) return false;
      if (ProgressionProfile != other.ProgressionProfile) return false;
      if (InitialProfile != other.InitialProfile) return false;
      if (EndStateProfile != other.EndStateProfile) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (BehaviorProfile.Length != 0) hash ^= BehaviorProfile.GetHashCode();
      if (AccountName.Length != 0) hash ^= AccountName.GetHashCode();
      if (ProgressionProfile.Length != 0) hash ^= ProgressionProfile.GetHashCode();
      if (InitialProfile.Length != 0) hash ^= InitialProfile.GetHashCode();
      if (EndStateProfile.Length != 0) hash ^= EndStateProfile.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (BehaviorProfile.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(BehaviorProfile);
      }
      if (AccountName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(AccountName);
      }
      if (ProgressionProfile.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ProgressionProfile);
      }
      if (InitialProfile.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(InitialProfile);
      }
      if (EndStateProfile.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(EndStateProfile);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (BehaviorProfile.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(BehaviorProfile);
      }
      if (AccountName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(AccountName);
      }
      if (ProgressionProfile.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ProgressionProfile);
      }
      if (InitialProfile.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(InitialProfile);
      }
      if (EndStateProfile.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(EndStateProfile);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (BehaviorProfile.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BehaviorProfile);
      }
      if (AccountName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AccountName);
      }
      if (ProgressionProfile.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ProgressionProfile);
      }
      if (InitialProfile.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(InitialProfile);
      }
      if (EndStateProfile.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EndStateProfile);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ActivityMember other) {
      if (other == null) {
        return;
      }
      if (other.BehaviorProfile.Length != 0) {
        BehaviorProfile = other.BehaviorProfile;
      }
      if (other.AccountName.Length != 0) {
        AccountName = other.AccountName;
      }
      if (other.ProgressionProfile.Length != 0) {
        ProgressionProfile = other.ProgressionProfile;
      }
      if (other.InitialProfile.Length != 0) {
        InitialProfile = other.InitialProfile;
      }
      if (other.EndStateProfile.Length != 0) {
        EndStateProfile = other.EndStateProfile;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            BehaviorProfile = input.ReadString();
            break;
          }
          case 18: {
            AccountName = input.ReadString();
            break;
          }
          case 26: {
            ProgressionProfile = input.ReadString();
            break;
          }
          case 34: {
            InitialProfile = input.ReadString();
            break;
          }
          case 42: {
            EndStateProfile = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            BehaviorProfile = input.ReadString();
            break;
          }
          case 18: {
            AccountName = input.ReadString();
            break;
          }
          case 26: {
            ProgressionProfile = input.ReadString();
            break;
          }
          case 34: {
            InitialProfile = input.ReadString();
            break;
          }
          case 42: {
            EndStateProfile = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ActivityMemberState : pb::IMessage<ActivityMemberState>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ActivityMemberState> _parser = new pb::MessageParser<ActivityMemberState>(() => new ActivityMemberState());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ActivityMemberState> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Communication.CommunicationReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActivityMemberState() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActivityMemberState(ActivityMemberState other) : this() {
      member_ = other.member_ != null ? other.member_.Clone() : null;
      guid_ = other.guid_;
      inRaid_ = other.inRaid_;
      petSpells_ = other.petSpells_.Clone();
      talents_ = other.talents_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActivityMemberState Clone() {
      return new ActivityMemberState(this);
    }

    /// <summary>Field number for the "member" field.</summary>
    public const int MemberFieldNumber = 1;
    private global::Communication.ActivityMember member_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Communication.ActivityMember Member {
      get { return member_; }
      set {
        member_ = value;
      }
    }

    /// <summary>Field number for the "guid" field.</summary>
    public const int GuidFieldNumber = 2;
    private ulong guid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Guid {
      get { return guid_; }
      set {
        guid_ = value;
      }
    }

    /// <summary>Field number for the "InRaid" field.</summary>
    public const int InRaidFieldNumber = 3;
    private bool inRaid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool InRaid {
      get { return inRaid_; }
      set {
        inRaid_ = value;
      }
    }

    /// <summary>Field number for the "PetSpells" field.</summary>
    public const int PetSpellsFieldNumber = 4;
    private static readonly pb::FieldCodec<uint> _repeated_petSpells_codec
        = pb::FieldCodec.ForUInt32(34);
    private readonly pbc::RepeatedField<uint> petSpells_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> PetSpells {
      get { return petSpells_; }
    }

    /// <summary>Field number for the "Talents" field.</summary>
    public const int TalentsFieldNumber = 5;
    private static readonly pb::FieldCodec<uint> _repeated_talents_codec
        = pb::FieldCodec.ForUInt32(42);
    private readonly pbc::RepeatedField<uint> talents_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> Talents {
      get { return talents_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ActivityMemberState);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ActivityMemberState other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Member, other.Member)) return false;
      if (Guid != other.Guid) return false;
      if (InRaid != other.InRaid) return false;
      if(!petSpells_.Equals(other.petSpells_)) return false;
      if(!talents_.Equals(other.talents_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (member_ != null) hash ^= Member.GetHashCode();
      if (Guid != 0UL) hash ^= Guid.GetHashCode();
      if (InRaid != false) hash ^= InRaid.GetHashCode();
      hash ^= petSpells_.GetHashCode();
      hash ^= talents_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (member_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Member);
      }
      if (Guid != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(Guid);
      }
      if (InRaid != false) {
        output.WriteRawTag(24);
        output.WriteBool(InRaid);
      }
      petSpells_.WriteTo(output, _repeated_petSpells_codec);
      talents_.WriteTo(output, _repeated_talents_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (member_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Member);
      }
      if (Guid != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(Guid);
      }
      if (InRaid != false) {
        output.WriteRawTag(24);
        output.WriteBool(InRaid);
      }
      petSpells_.WriteTo(ref output, _repeated_petSpells_codec);
      talents_.WriteTo(ref output, _repeated_talents_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (member_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Member);
      }
      if (Guid != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Guid);
      }
      if (InRaid != false) {
        size += 1 + 1;
      }
      size += petSpells_.CalculateSize(_repeated_petSpells_codec);
      size += talents_.CalculateSize(_repeated_talents_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ActivityMemberState other) {
      if (other == null) {
        return;
      }
      if (other.member_ != null) {
        if (member_ == null) {
          Member = new global::Communication.ActivityMember();
        }
        Member.MergeFrom(other.Member);
      }
      if (other.Guid != 0UL) {
        Guid = other.Guid;
      }
      if (other.InRaid != false) {
        InRaid = other.InRaid;
      }
      petSpells_.Add(other.petSpells_);
      talents_.Add(other.talents_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (member_ == null) {
              Member = new global::Communication.ActivityMember();
            }
            input.ReadMessage(Member);
            break;
          }
          case 16: {
            Guid = input.ReadUInt64();
            break;
          }
          case 24: {
            InRaid = input.ReadBool();
            break;
          }
          case 34:
          case 32: {
            petSpells_.AddEntriesFrom(input, _repeated_petSpells_codec);
            break;
          }
          case 42:
          case 40: {
            talents_.AddEntriesFrom(input, _repeated_talents_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (member_ == null) {
              Member = new global::Communication.ActivityMember();
            }
            input.ReadMessage(Member);
            break;
          }
          case 16: {
            Guid = input.ReadUInt64();
            break;
          }
          case 24: {
            InRaid = input.ReadBool();
            break;
          }
          case 34:
          case 32: {
            petSpells_.AddEntriesFrom(ref input, _repeated_petSpells_codec);
            break;
          }
          case 42:
          case 40: {
            talents_.AddEntriesFrom(ref input, _repeated_talents_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class WorldStateUpdate : pb::IMessage<WorldStateUpdate>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WorldStateUpdate> _parser = new pb::MessageParser<WorldStateUpdate>(() => new WorldStateUpdate());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WorldStateUpdate> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Communication.CommunicationReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorldStateUpdate() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorldStateUpdate(WorldStateUpdate other) : this() {
      action_ = other.action_;
      param1_ = other.param1_;
      param2_ = other.param2_;
      param3_ = other.param3_;
      param4_ = other.param4_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorldStateUpdate Clone() {
      return new WorldStateUpdate(this);
    }

    /// <summary>Field number for the "action" field.</summary>
    public const int ActionFieldNumber = 1;
    private global::Communication.ActivityAction action_ = global::Communication.ActivityAction.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Communication.ActivityAction Action {
      get { return action_; }
      set {
        action_ = value;
      }
    }

    /// <summary>Field number for the "param1" field.</summary>
    public const int Param1FieldNumber = 2;
    private string param1_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Param1 {
      get { return param1_; }
      set {
        param1_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "param2" field.</summary>
    public const int Param2FieldNumber = 3;
    private string param2_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Param2 {
      get { return param2_; }
      set {
        param2_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "param3" field.</summary>
    public const int Param3FieldNumber = 4;
    private string param3_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Param3 {
      get { return param3_; }
      set {
        param3_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "param4" field.</summary>
    public const int Param4FieldNumber = 5;
    private string param4_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Param4 {
      get { return param4_; }
      set {
        param4_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WorldStateUpdate);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WorldStateUpdate other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Action != other.Action) return false;
      if (Param1 != other.Param1) return false;
      if (Param2 != other.Param2) return false;
      if (Param3 != other.Param3) return false;
      if (Param4 != other.Param4) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Action != global::Communication.ActivityAction.None) hash ^= Action.GetHashCode();
      if (Param1.Length != 0) hash ^= Param1.GetHashCode();
      if (Param2.Length != 0) hash ^= Param2.GetHashCode();
      if (Param3.Length != 0) hash ^= Param3.GetHashCode();
      if (Param4.Length != 0) hash ^= Param4.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Action != global::Communication.ActivityAction.None) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Action);
      }
      if (Param1.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Param1);
      }
      if (Param2.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Param2);
      }
      if (Param3.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Param3);
      }
      if (Param4.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Param4);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Action != global::Communication.ActivityAction.None) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Action);
      }
      if (Param1.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Param1);
      }
      if (Param2.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Param2);
      }
      if (Param3.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Param3);
      }
      if (Param4.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Param4);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Action != global::Communication.ActivityAction.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Action);
      }
      if (Param1.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Param1);
      }
      if (Param2.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Param2);
      }
      if (Param3.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Param3);
      }
      if (Param4.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Param4);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WorldStateUpdate other) {
      if (other == null) {
        return;
      }
      if (other.Action != global::Communication.ActivityAction.None) {
        Action = other.Action;
      }
      if (other.Param1.Length != 0) {
        Param1 = other.Param1;
      }
      if (other.Param2.Length != 0) {
        Param2 = other.Param2;
      }
      if (other.Param3.Length != 0) {
        Param3 = other.Param3;
      }
      if (other.Param4.Length != 0) {
        Param4 = other.Param4;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Action = (global::Communication.ActivityAction) input.ReadEnum();
            break;
          }
          case 18: {
            Param1 = input.ReadString();
            break;
          }
          case 26: {
            Param2 = input.ReadString();
            break;
          }
          case 34: {
            Param3 = input.ReadString();
            break;
          }
          case 42: {
            Param4 = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Action = (global::Communication.ActivityAction) input.ReadEnum();
            break;
          }
          case 18: {
            Param1 = input.ReadString();
            break;
          }
          case 26: {
            Param2 = input.ReadString();
            break;
          }
          case 34: {
            Param3 = input.ReadString();
            break;
          }
          case 42: {
            Param4 = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
