namespace MaNGOSDBDomain.Models
{
    public class CreatureTemplate
    {
        public long Entry { get; set; }
        public string Name { get; set; }
        public string SubName { get; set; }
        public byte MinLevel { get; set; }
        public byte MaxLevel { get; set; }
        public int ModelId1 { get; set; }
        public int ModelId2 { get; set; }
        public int ModelId3 { get; set; }
        public int ModelId4 { get; set; }
        public short Faction { get; set; }
        public float Scale { get; set; }
        public byte Family { get; set; }
        public byte CreatureType { get; set; }
        public byte InhabitType { get; set; }
        public byte RegenerateStats { get; set; }
        public byte RacialLeader { get; set; }
        public int NpcFlags { get; set; }
        public int UnitFlags { get; set; }
        public int DynamicFlags { get; set; }
        public int ExtraFlags { get; set; }
        public int CreatureTypeFlags { get; set; }
        public float SpeedWalk { get; set; }
        public float SpeedRun { get; set; }
        public int Detection { get; set; }
        public int CallForHelp { get; set; }
        public int Pursuit { get; set; }
        public int Leash { get; set; }
        public int Timeout { get; set; }
        public byte UnitClass { get; set; }
        public byte Rank { get; set; }
        public float HealthMultiplier { get; set; }
        public float PowerMultiplier { get; set; }
        public float DamageMultiplier { get; set; }
        public float DamageVariance { get; set; }
        public float ArmorMultiplier { get; set; }
        public float ExperienceMultiplier { get; set; }
        public int MinLevelHealth { get; set; }
        public int MaxLevelHealth { get; set; }
        public int MinLevelMana { get; set; }
        public int MaxLevelMana { get; set; }
        public float MinMeleeDmg { get; set; }
        public float MaxMeleeDmg { get; set; }
        public float MinRangedDmg { get; set; }
        public float MaxRangedDmg { get; set; }
        public int Armor { get; set; }
        public int MeleeAttackPower { get; set; }
        public short RangedAttackPower { get; set; }
        public int MeleeBaseAttackTime { get; set; }
        public int RangedBaseAttackTime { get; set; }
        public byte DamageSchool { get; set; }
        public int MinLootGold { get; set; }
        public int MaxLootGold { get; set; }
        public int LootId { get; set; }
        public int PickpocketLootId { get; set; }
        public int SkinningLootId { get; set; }
        public int KillCredit1 { get; set; }
        public int KillCredit2 { get; set; }
        public int MechanicImmuneMask { get; set; }
        public int SchoolImmuneMask { get; set; }
        public int ResistanceHoly { get; set; }
        public int ResistanceFire { get; set; }
        public int ResistanceNature { get; set; }
        public int ResistanceFrost { get; set; }
        public int ResistanceShadow { get; set; }
        public int ResistanceArcane { get; set; }
        public int PetSpellDataId { get; set; }
        public byte MovementType { get; set; }
        public byte TrainerType { get; set; }
        public int TrainerSpell { get; set; }
        public byte TrainerClass { get; set; }
        public byte TrainerRace { get; set; }
        public int TrainerTemplateId { get; set; }
        public int VendorTemplateId { get; set; }
        public int GossipMenuId { get; set; }
        public int InteractionPauseTimer { get; set; }
        public byte VisibilityDistanceType { get; set; }
        public int CorpseDecay { get; set; }
        public int SpellList { get; set; }
        public int EquipmentTemplateId { get; set; }
        public byte Civilian { get; set; }
        public string AIName { get; set; }
        public string ScriptName { get; set; }
    }
}
