// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: state.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace State {

  /// <summary>Holder for reflection information generated from state.proto</summary>
  public static partial class StateReflection {

    #region Descriptor
    /// <summary>File descriptor for state.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StateReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtzdGF0ZS5wcm90bxIFc3RhdGUaD2NoYXJhY3Rlci5wcm90byJrCg9jaGFy",
            "YWN0ZXJfc3RhdGUSKwoNZGVzaXJlZF9zdGF0ZRgBIAEoCzIULmNoYXJhY3Rl",
            "ci5jaGFyYWN0ZXISKwoNY3VycmVudF9zdGF0ZRgCIAEoCzIULmNoYXJhY3Rl",
            "ci5jaGFyYWN0ZXJiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Character.CharacterReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::State.character_state), global::State.character_state.Parser, new[]{ "DesiredState", "CurrentState" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class character_state : pb::IMessage<character_state>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<character_state> _parser = new pb::MessageParser<character_state>(() => new character_state());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<character_state> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::State.StateReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public character_state() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public character_state(character_state other) : this() {
      desiredState_ = other.desiredState_ != null ? other.desiredState_.Clone() : null;
      currentState_ = other.currentState_ != null ? other.currentState_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public character_state Clone() {
      return new character_state(this);
    }

    /// <summary>Field number for the "desired_state" field.</summary>
    public const int DesiredStateFieldNumber = 1;
    private global::Character.character desiredState_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Character.character DesiredState {
      get { return desiredState_; }
      set {
        desiredState_ = value;
      }
    }

    /// <summary>Field number for the "current_state" field.</summary>
    public const int CurrentStateFieldNumber = 2;
    private global::Character.character currentState_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Character.character CurrentState {
      get { return currentState_; }
      set {
        currentState_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as character_state);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(character_state other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(DesiredState, other.DesiredState)) return false;
      if (!object.Equals(CurrentState, other.CurrentState)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (desiredState_ != null) hash ^= DesiredState.GetHashCode();
      if (currentState_ != null) hash ^= CurrentState.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (desiredState_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(DesiredState);
      }
      if (currentState_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(CurrentState);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (desiredState_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(DesiredState);
      }
      if (currentState_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(CurrentState);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (desiredState_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DesiredState);
      }
      if (currentState_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CurrentState);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(character_state other) {
      if (other == null) {
        return;
      }
      if (other.desiredState_ != null) {
        if (desiredState_ == null) {
          DesiredState = new global::Character.character();
        }
        DesiredState.MergeFrom(other.DesiredState);
      }
      if (other.currentState_ != null) {
        if (currentState_ == null) {
          CurrentState = new global::Character.character();
        }
        CurrentState.MergeFrom(other.CurrentState);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (desiredState_ == null) {
              DesiredState = new global::Character.character();
            }
            input.ReadMessage(DesiredState);
            break;
          }
          case 18: {
            if (currentState_ == null) {
              CurrentState = new global::Character.character();
            }
            input.ReadMessage(CurrentState);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (desiredState_ == null) {
              DesiredState = new global::Character.character();
            }
            input.ReadMessage(DesiredState);
            break;
          }
          case 18: {
            if (currentState_ == null) {
              CurrentState = new global::Character.character();
            }
            input.ReadMessage(CurrentState);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
