// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: communication.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Communication {

  /// <summary>Holder for reflection information generated from communication.proto</summary>
  public static partial class CommunicationReflection {

    #region Descriptor
    /// <summary>File descriptor for communication.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CommunicationReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNjb21tdW5pY2F0aW9uLnByb3RvEg1jb21tdW5pY2F0aW9uGgtzdGF0ZS5w",
            "cm90byLLAQoLRGF0YU1lc3NhZ2USEgoKc2VydmljZV9pZBgBIAEoCRIjCgZ3",
            "c3RhdGUYAiABKAsyES5zdGF0ZS5Xb3JsZFN0YXRlSAASJgoGYXN0YXRlGAMg",
            "ASgLMhQuc3RhdGUuQWN0aXZpdHlTdGF0ZUgBEicKBmNzdGF0ZRgEIAEoCzIV",
            "LnN0YXRlLkNoYXJhY3RlclN0YXRlSAJCDQoLd29ybGRfc3RhdGVCEAoOYWN0",
            "aXZpdHlfc3RhdGVCEQoPY2hhcmFjdGVyX3N0YXRlIj8KDkNvbnRyb2xNZXNz",
            "YWdlEhIKCmVycm9yX2NvZGUYASABKAUSGQoRZXJyb3JfZGVzY3JpcHRpb24Y",
            "AiABKAkigwEKEFVuaXZlcnNhbE1lc3NhZ2USKgoEZGF0YRgBIAEoCzIaLmNv",
            "bW11bmljYXRpb24uRGF0YU1lc3NhZ2VIABIwCgdjb250cm9sGAIgASgLMh0u",
            "Y29tbXVuaWNhdGlvbi5Db250cm9sTWVzc2FnZUgAQhEKD21lc3NhZ2VfY29u",
            "dGVudGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::State.StateReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Communication.DataMessage), global::Communication.DataMessage.Parser, new[]{ "ServiceId", "Wstate", "Astate", "Cstate" }, new[]{ "WorldState", "ActivityState", "CharacterState" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Communication.ControlMessage), global::Communication.ControlMessage.Parser, new[]{ "ErrorCode", "ErrorDescription" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Communication.UniversalMessage), global::Communication.UniversalMessage.Parser, new[]{ "Data", "Control" }, new[]{ "MessageContent" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Message that can carry a variety of payload types
  /// </summary>
  public sealed partial class DataMessage : pb::IMessage<DataMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DataMessage> _parser = new pb::MessageParser<DataMessage>(() => new DataMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DataMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Communication.CommunicationReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DataMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DataMessage(DataMessage other) : this() {
      serviceId_ = other.serviceId_;
      switch (other.WorldStateCase) {
        case WorldStateOneofCase.Wstate:
          Wstate = other.Wstate.Clone();
          break;
      }

      switch (other.ActivityStateCase) {
        case ActivityStateOneofCase.Astate:
          Astate = other.Astate.Clone();
          break;
      }

      switch (other.CharacterStateCase) {
        case CharacterStateOneofCase.Cstate:
          Cstate = other.Cstate.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DataMessage Clone() {
      return new DataMessage(this);
    }

    /// <summary>Field number for the "service_id" field.</summary>
    public const int ServiceIdFieldNumber = 1;
    private string serviceId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ServiceId {
      get { return serviceId_; }
      set {
        serviceId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "wstate" field.</summary>
    public const int WstateFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::State.WorldState Wstate {
      get { return worldStateCase_ == WorldStateOneofCase.Wstate ? (global::State.WorldState) worldState_ : null; }
      set {
        worldState_ = value;
        worldStateCase_ = value == null ? WorldStateOneofCase.None : WorldStateOneofCase.Wstate;
      }
    }

    /// <summary>Field number for the "astate" field.</summary>
    public const int AstateFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::State.ActivityState Astate {
      get { return activityStateCase_ == ActivityStateOneofCase.Astate ? (global::State.ActivityState) activityState_ : null; }
      set {
        activityState_ = value;
        activityStateCase_ = value == null ? ActivityStateOneofCase.None : ActivityStateOneofCase.Astate;
      }
    }

    /// <summary>Field number for the "cstate" field.</summary>
    public const int CstateFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::State.CharacterState Cstate {
      get { return characterStateCase_ == CharacterStateOneofCase.Cstate ? (global::State.CharacterState) characterState_ : null; }
      set {
        characterState_ = value;
        characterStateCase_ = value == null ? CharacterStateOneofCase.None : CharacterStateOneofCase.Cstate;
      }
    }

    private object worldState_;
    /// <summary>Enum of possible cases for the "world_state" oneof.</summary>
    public enum WorldStateOneofCase {
      None = 0,
      Wstate = 2,
    }
    private WorldStateOneofCase worldStateCase_ = WorldStateOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorldStateOneofCase WorldStateCase {
      get { return worldStateCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearWorldState() {
      worldStateCase_ = WorldStateOneofCase.None;
      worldState_ = null;
    }

    private object activityState_;
    /// <summary>Enum of possible cases for the "activity_state" oneof.</summary>
    public enum ActivityStateOneofCase {
      None = 0,
      Astate = 3,
    }
    private ActivityStateOneofCase activityStateCase_ = ActivityStateOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActivityStateOneofCase ActivityStateCase {
      get { return activityStateCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearActivityState() {
      activityStateCase_ = ActivityStateOneofCase.None;
      activityState_ = null;
    }

    private object characterState_;
    /// <summary>Enum of possible cases for the "character_state" oneof.</summary>
    public enum CharacterStateOneofCase {
      None = 0,
      Cstate = 4,
    }
    private CharacterStateOneofCase characterStateCase_ = CharacterStateOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CharacterStateOneofCase CharacterStateCase {
      get { return characterStateCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearCharacterState() {
      characterStateCase_ = CharacterStateOneofCase.None;
      characterState_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DataMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DataMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ServiceId != other.ServiceId) return false;
      if (!object.Equals(Wstate, other.Wstate)) return false;
      if (!object.Equals(Astate, other.Astate)) return false;
      if (!object.Equals(Cstate, other.Cstate)) return false;
      if (WorldStateCase != other.WorldStateCase) return false;
      if (ActivityStateCase != other.ActivityStateCase) return false;
      if (CharacterStateCase != other.CharacterStateCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ServiceId.Length != 0) hash ^= ServiceId.GetHashCode();
      if (worldStateCase_ == WorldStateOneofCase.Wstate) hash ^= Wstate.GetHashCode();
      if (activityStateCase_ == ActivityStateOneofCase.Astate) hash ^= Astate.GetHashCode();
      if (characterStateCase_ == CharacterStateOneofCase.Cstate) hash ^= Cstate.GetHashCode();
      hash ^= (int) worldStateCase_;
      hash ^= (int) activityStateCase_;
      hash ^= (int) characterStateCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ServiceId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ServiceId);
      }
      if (worldStateCase_ == WorldStateOneofCase.Wstate) {
        output.WriteRawTag(18);
        output.WriteMessage(Wstate);
      }
      if (activityStateCase_ == ActivityStateOneofCase.Astate) {
        output.WriteRawTag(26);
        output.WriteMessage(Astate);
      }
      if (characterStateCase_ == CharacterStateOneofCase.Cstate) {
        output.WriteRawTag(34);
        output.WriteMessage(Cstate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ServiceId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ServiceId);
      }
      if (worldStateCase_ == WorldStateOneofCase.Wstate) {
        output.WriteRawTag(18);
        output.WriteMessage(Wstate);
      }
      if (activityStateCase_ == ActivityStateOneofCase.Astate) {
        output.WriteRawTag(26);
        output.WriteMessage(Astate);
      }
      if (characterStateCase_ == CharacterStateOneofCase.Cstate) {
        output.WriteRawTag(34);
        output.WriteMessage(Cstate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ServiceId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ServiceId);
      }
      if (worldStateCase_ == WorldStateOneofCase.Wstate) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Wstate);
      }
      if (activityStateCase_ == ActivityStateOneofCase.Astate) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Astate);
      }
      if (characterStateCase_ == CharacterStateOneofCase.Cstate) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Cstate);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DataMessage other) {
      if (other == null) {
        return;
      }
      if (other.ServiceId.Length != 0) {
        ServiceId = other.ServiceId;
      }
      switch (other.WorldStateCase) {
        case WorldStateOneofCase.Wstate:
          if (Wstate == null) {
            Wstate = new global::State.WorldState();
          }
          Wstate.MergeFrom(other.Wstate);
          break;
      }

      switch (other.ActivityStateCase) {
        case ActivityStateOneofCase.Astate:
          if (Astate == null) {
            Astate = new global::State.ActivityState();
          }
          Astate.MergeFrom(other.Astate);
          break;
      }

      switch (other.CharacterStateCase) {
        case CharacterStateOneofCase.Cstate:
          if (Cstate == null) {
            Cstate = new global::State.CharacterState();
          }
          Cstate.MergeFrom(other.Cstate);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ServiceId = input.ReadString();
            break;
          }
          case 18: {
            global::State.WorldState subBuilder = new global::State.WorldState();
            if (worldStateCase_ == WorldStateOneofCase.Wstate) {
              subBuilder.MergeFrom(Wstate);
            }
            input.ReadMessage(subBuilder);
            Wstate = subBuilder;
            break;
          }
          case 26: {
            global::State.ActivityState subBuilder = new global::State.ActivityState();
            if (activityStateCase_ == ActivityStateOneofCase.Astate) {
              subBuilder.MergeFrom(Astate);
            }
            input.ReadMessage(subBuilder);
            Astate = subBuilder;
            break;
          }
          case 34: {
            global::State.CharacterState subBuilder = new global::State.CharacterState();
            if (characterStateCase_ == CharacterStateOneofCase.Cstate) {
              subBuilder.MergeFrom(Cstate);
            }
            input.ReadMessage(subBuilder);
            Cstate = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ServiceId = input.ReadString();
            break;
          }
          case 18: {
            global::State.WorldState subBuilder = new global::State.WorldState();
            if (worldStateCase_ == WorldStateOneofCase.Wstate) {
              subBuilder.MergeFrom(Wstate);
            }
            input.ReadMessage(subBuilder);
            Wstate = subBuilder;
            break;
          }
          case 26: {
            global::State.ActivityState subBuilder = new global::State.ActivityState();
            if (activityStateCase_ == ActivityStateOneofCase.Astate) {
              subBuilder.MergeFrom(Astate);
            }
            input.ReadMessage(subBuilder);
            Astate = subBuilder;
            break;
          }
          case 34: {
            global::State.CharacterState subBuilder = new global::State.CharacterState();
            if (characterStateCase_ == CharacterStateOneofCase.Cstate) {
              subBuilder.MergeFrom(Cstate);
            }
            input.ReadMessage(subBuilder);
            Cstate = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Message used for controlling communication and reporting errors
  /// </summary>
  public sealed partial class ControlMessage : pb::IMessage<ControlMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ControlMessage> _parser = new pb::MessageParser<ControlMessage>(() => new ControlMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ControlMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Communication.CommunicationReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ControlMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ControlMessage(ControlMessage other) : this() {
      errorCode_ = other.errorCode_;
      errorDescription_ = other.errorDescription_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ControlMessage Clone() {
      return new ControlMessage(this);
    }

    /// <summary>Field number for the "error_code" field.</summary>
    public const int ErrorCodeFieldNumber = 1;
    private int errorCode_;
    /// <summary>
    /// Error code
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ErrorCode {
      get { return errorCode_; }
      set {
        errorCode_ = value;
      }
    }

    /// <summary>Field number for the "error_description" field.</summary>
    public const int ErrorDescriptionFieldNumber = 2;
    private string errorDescription_ = "";
    /// <summary>
    /// Human-readable description of the error
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ErrorDescription {
      get { return errorDescription_; }
      set {
        errorDescription_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ControlMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ControlMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ErrorCode != other.ErrorCode) return false;
      if (ErrorDescription != other.ErrorDescription) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ErrorCode != 0) hash ^= ErrorCode.GetHashCode();
      if (ErrorDescription.Length != 0) hash ^= ErrorDescription.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ErrorCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ErrorCode);
      }
      if (ErrorDescription.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ErrorDescription);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ErrorCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ErrorCode);
      }
      if (ErrorDescription.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ErrorDescription);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ErrorCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ErrorCode);
      }
      if (ErrorDescription.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ErrorDescription);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ControlMessage other) {
      if (other == null) {
        return;
      }
      if (other.ErrorCode != 0) {
        ErrorCode = other.ErrorCode;
      }
      if (other.ErrorDescription.Length != 0) {
        ErrorDescription = other.ErrorDescription;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ErrorCode = input.ReadInt32();
            break;
          }
          case 18: {
            ErrorDescription = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ErrorCode = input.ReadInt32();
            break;
          }
          case 18: {
            ErrorDescription = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Universal message format that encapsulates various types of messages
  /// </summary>
  public sealed partial class UniversalMessage : pb::IMessage<UniversalMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UniversalMessage> _parser = new pb::MessageParser<UniversalMessage>(() => new UniversalMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UniversalMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Communication.CommunicationReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UniversalMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UniversalMessage(UniversalMessage other) : this() {
      switch (other.MessageContentCase) {
        case MessageContentOneofCase.Data:
          Data = other.Data.Clone();
          break;
        case MessageContentOneofCase.Control:
          Control = other.Control.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UniversalMessage Clone() {
      return new UniversalMessage(this);
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Communication.DataMessage Data {
      get { return messageContentCase_ == MessageContentOneofCase.Data ? (global::Communication.DataMessage) messageContent_ : null; }
      set {
        messageContent_ = value;
        messageContentCase_ = value == null ? MessageContentOneofCase.None : MessageContentOneofCase.Data;
      }
    }

    /// <summary>Field number for the "control" field.</summary>
    public const int ControlFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Communication.ControlMessage Control {
      get { return messageContentCase_ == MessageContentOneofCase.Control ? (global::Communication.ControlMessage) messageContent_ : null; }
      set {
        messageContent_ = value;
        messageContentCase_ = value == null ? MessageContentOneofCase.None : MessageContentOneofCase.Control;
      }
    }

    private object messageContent_;
    /// <summary>Enum of possible cases for the "message_content" oneof.</summary>
    public enum MessageContentOneofCase {
      None = 0,
      Data = 1,
      Control = 2,
    }
    private MessageContentOneofCase messageContentCase_ = MessageContentOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MessageContentOneofCase MessageContentCase {
      get { return messageContentCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMessageContent() {
      messageContentCase_ = MessageContentOneofCase.None;
      messageContent_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UniversalMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UniversalMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Data, other.Data)) return false;
      if (!object.Equals(Control, other.Control)) return false;
      if (MessageContentCase != other.MessageContentCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (messageContentCase_ == MessageContentOneofCase.Data) hash ^= Data.GetHashCode();
      if (messageContentCase_ == MessageContentOneofCase.Control) hash ^= Control.GetHashCode();
      hash ^= (int) messageContentCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (messageContentCase_ == MessageContentOneofCase.Data) {
        output.WriteRawTag(10);
        output.WriteMessage(Data);
      }
      if (messageContentCase_ == MessageContentOneofCase.Control) {
        output.WriteRawTag(18);
        output.WriteMessage(Control);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (messageContentCase_ == MessageContentOneofCase.Data) {
        output.WriteRawTag(10);
        output.WriteMessage(Data);
      }
      if (messageContentCase_ == MessageContentOneofCase.Control) {
        output.WriteRawTag(18);
        output.WriteMessage(Control);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (messageContentCase_ == MessageContentOneofCase.Data) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Data);
      }
      if (messageContentCase_ == MessageContentOneofCase.Control) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Control);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UniversalMessage other) {
      if (other == null) {
        return;
      }
      switch (other.MessageContentCase) {
        case MessageContentOneofCase.Data:
          if (Data == null) {
            Data = new global::Communication.DataMessage();
          }
          Data.MergeFrom(other.Data);
          break;
        case MessageContentOneofCase.Control:
          if (Control == null) {
            Control = new global::Communication.ControlMessage();
          }
          Control.MergeFrom(other.Control);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::Communication.DataMessage subBuilder = new global::Communication.DataMessage();
            if (messageContentCase_ == MessageContentOneofCase.Data) {
              subBuilder.MergeFrom(Data);
            }
            input.ReadMessage(subBuilder);
            Data = subBuilder;
            break;
          }
          case 18: {
            global::Communication.ControlMessage subBuilder = new global::Communication.ControlMessage();
            if (messageContentCase_ == MessageContentOneofCase.Control) {
              subBuilder.MergeFrom(Control);
            }
            input.ReadMessage(subBuilder);
            Control = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::Communication.DataMessage subBuilder = new global::Communication.DataMessage();
            if (messageContentCase_ == MessageContentOneofCase.Data) {
              subBuilder.MergeFrom(Data);
            }
            input.ReadMessage(subBuilder);
            Data = subBuilder;
            break;
          }
          case 18: {
            global::Communication.ControlMessage subBuilder = new global::Communication.ControlMessage();
            if (messageContentCase_ == MessageContentOneofCase.Control) {
              subBuilder.MergeFrom(Control);
            }
            input.ReadMessage(subBuilder);
            Control = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
