namespace WoWBot.Client.Models
{
    public class QuestTemplate
    {
        public int Entry { get; set; }
        public byte Method { get; set; }
        public short ZoneOrSort { get; set; }
        public byte MinLevel { get; set; }
        public byte MaxLevel { get; set; }
        public short QuestLevel { get; set; }
        public short Type { get; set; }
        public short RequiredClasses { get; set; }
        public short RequiredRaces { get; set; }
        public short RequiredSkill { get; set; }
        public short RequiredSkillValue { get; set; }
        public int RequiredCondition { get; set; }
        public short RepObjectiveFaction { get; set; }
        public int RepObjectiveValue { get; set; }
        public short RequiredMinRepFaction { get; set; }
        public int RequiredMinRepValue { get; set; }
        public short RequiredMaxRepFaction { get; set; }
        public int RequiredMaxRepValue { get; set; }
        public byte SuggestedPlayers { get; set; }
        public int LimitTime { get; set; }
        public short QuestFlags { get; set; }
        public byte SpecialFlags { get; set; }
        public int PrevQuestId { get; set; }
        public int NextQuestId { get; set; }
        public int ExclusiveGroup { get; set; }
        public int BreadcrumbForQuestId { get; set; }
        public int NextQuestInChain { get; set; }
        public int SrcItemId { get; set; }
        public byte SrcItemCount { get; set; }
        public int SrcSpell { get; set; }
        public string Title { get; set; }
        public string Details { get; set; }
        public string Objectives { get; set; }
        public string OfferRewardText { get; set; }
        public string RequestItemsText { get; set; }
        public string EndText { get; set; }
        public string ObjectiveText1 { get; set; }
        public string ObjectiveText2 { get; set; }
        public string ObjectiveText3 { get; set; }
        public string ObjectiveText4 { get; set; }
        public int ReqItemId1 { get; set; }
        public int ReqItemId2 { get; set; }
        public int ReqItemId3 { get; set; }
        public int ReqItemId4 { get; set; }
        public short ReqItemCount1 { get; set; }
        public short ReqItemCount2 { get; set; }
        public short ReqItemCount3 { get; set; }
        public short ReqItemCount4 { get; set; }
        public int ReqSourceId1 { get; set; }
        public int ReqSourceId2 { get; set; }
        public int ReqSourceId3 { get; set; }
        public int ReqSourceId4 { get; set; }
        public short ReqSourceCount1 { get; set; }
        public short ReqSourceCount2 { get; set; }
        public short ReqSourceCount3 { get; set; }
        public short ReqSourceCount4 { get; set; }
        public int ReqCreatureOrGOId1 { get; set; }
        public int ReqCreatureOrGOId2 { get; set; }
        public int ReqCreatureOrGOId3 { get; set; }
        public int ReqCreatureOrGOId4 { get; set; }
        public short ReqCreatureOrGOCount1 { get; set; }
        public short ReqCreatureOrGOCount2 { get; set; }
        public short ReqCreatureOrGOCount3 { get; set; }
        public short ReqCreatureOrGOCount4 { get; set; }
        public int ReqSpellCast1 { get; set; }
        public int ReqSpellCast2 { get; set; }
        public int ReqSpellCast3 { get; set; }
        public int ReqSpellCast4 { get; set; }
        public ulong RewChoiceItemId1 { get; set; }
        public ulong RewChoiceItemId2 { get; set; }
        public ulong RewChoiceItemId3 { get; set; }
        public ulong RewChoiceItemId4 { get; set; }
        public ulong RewChoiceItemId5 { get; set; }
        public ulong RewChoiceItemId6 { get; set; }
        public short RewChoiceItemCount1 { get; set; }
        public short RewChoiceItemCount2 { get; set; }
        public short RewChoiceItemCount3 { get; set; }
        public short RewChoiceItemCount4 { get; set; }
        public short RewChoiceItemCount5 { get; set; }
        public short RewChoiceItemCount6 { get; set; }
        public int RewItemId1 { get; set; }
        public int RewItemId2 { get; set; }
        public int RewItemId3 { get; set; }
        public int RewItemId4 { get; set; }
        public short RewItemCount1 { get; set; }
        public short RewItemCount2 { get; set; }
        public short RewItemCount3 { get; set; }
        public short RewItemCount4 { get; set; }
        public short RewRepFaction1 { get; set; }
        public short RewRepFaction2 { get; set; }
        public short RewRepFaction3 { get; set; }
        public short RewRepFaction4 { get; set; }
        public short RewRepFaction5 { get; set; }
        public int RewRepValue1 { get; set; }
        public int RewRepValue2 { get; set; }
        public int RewRepValue3 { get; set; }
        public int RewRepValue4 { get; set; }
        public int RewRepValue5 { get; set; }
        public int RewOrReqMoney { get; set; }
        public uint RewMoneyMaxLevel { get; set; }
        public int RewSpell { get; set; }
        public int RewSpellCast { get; set; }
        public int RewMailTemplateId { get; set; }
        public uint RewMailDelaySecs { get; set; }
        public ushort PointMapId { get; set; }
        public float PointX { get; set; }
        public float PointY { get; set; }
        public uint PointOpt { get; set; }
        public ushort DetailsEmote1 { get; set; }
        public ushort DetailsEmote2 { get; set; }
        public ushort DetailsEmote3 { get; set; }
        public ushort DetailsEmote4 { get; set; }
        public int DetailsEmoteDelay1 { get; set; }
        public int DetailsEmoteDelay2 { get; set; }
        public int DetailsEmoteDelay3 { get; set; }
        public int DetailsEmoteDelay4 { get; set; }
        public ushort IncompleteEmote { get; set; }
        public int IncompleteEmoteDelay { get; set; }
        public ushort CompleteEmote { get; set; }
        public int CompleteEmoteDelay { get; set; }
        public ushort OfferRewardEmote1 { get; set; }
        public ushort OfferRewardEmote2 { get; set; }
        public ushort OfferRewardEmote3 { get; set; }
        public ushort OfferRewardEmote4 { get; set; }
        public int OfferRewardEmoteDelay1 { get; set; }
        public int OfferRewardEmoteDelay2 { get; set; }
        public int OfferRewardEmoteDelay3 { get; set; }
        public int OfferRewardEmoteDelay4 { get; set; }
        public int StartScript { get; set; }
        public int CompleteScript { get; set; }
    }
}
